'use client';

import { useState } from 'react';
import { FileDown, Loader2, DownloadCloud } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { ProtectedRoute } from '@/components/ProtectedRoute';

export default function ExportsPage() {
  const [isExporting, setIsExporting] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState('');
  const [status, setStatus] = useState<string | null>(null);

  const handleExport = async () => {
    if (!selectedMonth) {
      alert('Please select a month to export.');
      return;
    }

    try {
      setIsExporting(true);
      setStatus('Generating report...');

      const res = await apiFetch(`/exports/monthly-pack`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${localStorage.getItem('token') || ''}`,
        },
        body: JSON.stringify({ month: selectedMonth }),
      });

      if (!res.ok) throw new Error(`Export failed: ${res.statusText}`);

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `radinate_report_${selectedMonth}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      setStatus('✅ Report downloaded successfully.');
    } catch (error: any) {
      console.error(error);
      setStatus(`❌ ${error.message}`);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <ProtectedRoute allowedRoles={['CMIO', 'Chief Risk Officer', 'CFO']}>
      <div className="p-6 bg-gray-50 dark:bg-gray-900 min-h-screen transition-colors">

        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold flex items-center gap-2 text-gray-800 dark:text-gray-200">
            <DownloadCloud className="text-green-600 dark:text-green-400" />
            Monthly Exports
          </h1>
        </div>

        {/* Form Section */}
        <div className="bg-white dark:bg-gray-800 shadow dark:shadow-lg border border-gray-200 dark:border-gray-700 rounded-lg p-6 max-w-lg mx-auto transition-colors">
          
          <h2 className="text-lg font-semibold mb-4 text-gray-700 dark:text-gray-200">
            📦 Generate Monthly Report Pack
          </h2>

          <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
            Export includes performance metrics, drift signals, and fairness metrics as CSV/PDF files.
          </p>

          <div className="flex flex-col space-y-4">

            {/* Month Selector */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Select Month
              </label>

              <input
                type="month"
                value={selectedMonth}
                onChange={(e) => setSelectedMonth(e.target.value)}
                className="
                  border border-gray-300 dark:border-gray-600 
                  bg-white dark:bg-gray-700 text-gray-800 dark:text-gray-200 
                  rounded-md p-2 w-full 
                  focus:ring-2 focus:ring-green-500 focus:outline-none
                  transition-colors
                "
              />
            </div>

            {/* Export Button */}
            <button
              onClick={handleExport}
              disabled={isExporting}
              className={`flex items-center justify-center gap-2 px-4 py-2 rounded-md text-white font-medium transition
                ${
                  isExporting
                    ? 'bg-gray-400 dark:bg-gray-600 cursor-not-allowed'
                    : 'bg-green-600 dark:bg-green-700 hover:bg-green-700 dark:hover:bg-green-600'
                }
              `}
            >
              {isExporting ? (
                <>
                  <Loader2 className="animate-spin" /> Generating...
                </>
              ) : (
                <>
                  <FileDown /> Download Report Pack
                </>
              )}
            </button>
          </div>

          {/* Status Message */}
          {status && (
            <div
              className={`mt-4 text-sm font-medium ${
                status.startsWith('✅')
                  ? 'text-green-600 dark:text-green-400'
                  : status.startsWith('❌')
                  ? 'text-red-600 dark:text-red-400'
                  : 'text-gray-600 dark:text-gray-300'
              }`}
            >
              {status}
            </div>
          )}
        </div>

        {/* Info Section */}
        <div className="mt-10 text-sm text-gray-600 dark:text-gray-400 text-center">
          <p>
            Reports are generated by Radinate backend based on the most recent job and metric data.
          </p>
          <p className="mt-1">
            Accessible to roles: <b>CMIO, Chief Risk Officer, CFO</b>
          </p>
        </div>
      </div>
    </ProtectedRoute>
  );
}
